name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile \
            --add-data "fabric_tracker.db;." \
            --add-data "fabric_tracker_tk/ui_dashboard.py;." \
            --add-data "fabric_tracker_tk/ui_entries.py;." \
            --add-data "fabric_tracker_tk/ui_masters.py;." \
            --add-data "fabric_tracker_tk/ui_fabricators.py;." \
            --add-data "fabric_tracker_tk/ui_customers.py;." \
            --add-data "fabric_tracker_tk/ui_fabrics.py;." \
            --add-data "fabric_tracker_tk/ui_purchases.py;." \
            --add-data "fabric_tracker_tk/ui_sales.py;." \
            --add-data "fabric_tracker_tk/ui_stock.py;." \
            --add-data "fabric_tracker_tk/ui_suppliers.py;." \
            --add-data "fabric_tracker_tk/ui_yarn_types.py;." \
            fabric_tracker_tk/main.py --name fabric_tracker

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fabric-tracker-windows
          path: dist/fabric_tracker.exe
